export const state = {
  audioCtx: null,
  analyser: null,
  dataArray: null,
  masterAudioElement: null,
  mediaSourceNode: null,
  isPlaying: false,
  synthTimer: null,
  synthTimeElapsed: 0,
  audioSourceType: 'synth',
  selectedPreset: 'cyberpunk',
  currentGeometryMode: 'wave',
  isShuffle: false,
  repeatMode: 'all',
  currentVolume: 0.85,
  isMuted: false,
  isDraggingScrubber: false,
  currentTrackIndex: 0,
  mouseX: 0,
  mouseY: 0,
  targetX: 0,
  targetY: 0,
  time: 0,
  themeSpeed: 1.0,
  themeWaveIntensity: 1.5,
  currentEnergy: 0.0,
  targetEnergy: 0.0,
  cameraBaseZ: 45,
  cameraBaseY: 18,
  playlist: [],
  SYNTH_PRESETS: ['cyberpunk', 'lofi', 'ambient', 'electro']
};
